### ISSUE TITLE
Crash after updating to v0.7.7 (data problem)

### ISSUE THREAD

**Issue by racuna** [renyuneyun/Easer#228]
**Describe the bug**
v. 0.7.7, 0.7.7.1-BETA and 0.7.7.1 can't run previous version scripts

**To Reproduce**
1. Go to F-Droid and update
2. Easer will crash. 
3. Delete all data from Easer
4. All permissions granted again.
5. Import scripts from previous version.
6. Try to convert to recommended format.
7. Crash again.

I currently downgraded Easer to 0.7.6.2

**Comment by twikedk** [comment]
I tried with 0.7.7 and 0.7.7.1 and ended with the same result as @racuna. This is on Android 5.1

**Comment by renyuneyun** [comment]
Thanks for reporting.
@racuna are you also on Android 5.1?

I guess this is due to v0.7.7. What Event and Condition do you use?

**Comment by racuna** [comment]
No, I'm on Android Pie 9 (MIUI 10.3.1.0)

I'm not using events, just Conditions and their reverse scenarios:
- Connected to internet (Not Connected)
- Connected to wifi
- Time
- Day of the week
- Charging

**Comment by racuna** [comment]
I updated to 0.7.7.2, with the same problem. I can't copy text from error
so I took a screenshot (attached).

Also, I can't go back to 0.7.6.2 because its not appear on f-droid anymore.

**Comment by twikedk** [comment]
@racuna older versions should be available in F-Droid if you enable archive repository. That said it seems that 0.7.6.x are missing but 0.7.6 is available (that is the one I'm using now)

**Comment by racuna** [comment]
@twikedk  thanks, I did activate the archive, I'm back to 0.7.6.1 now. Regards.

**Comment by racuna** [comment]
I'm attaching logs, using 0.7.7.3 (crash still happening in this version)

[2019_06_27_15_55_13.log](https://github.com/renyuneyun/Easer/files/3336502/2019_06_27_15_55_13.log)
[2019_06_27_15_57_03.log](https://github.com/renyuneyun/Easer/files/3336503/2019_06_27_15_57_03.log)
[2019_06_27_15_57_14.log](https://github.com/renyuneyun/Easer/files/3336504/2019_06_27_15_57_14.log)

**Comment by gruentee** [comment]
I can confirm this on Android 9.1. I experienced the exact same problem as you, @racuna

**Comment by X-dark** [comment]
I suspect this to be related to #188 
For me configuring wifi was crashing the app when using event but working fine when using condition. As I understood from changelog, 0.7.7 merged Events and Conditions, this may then be related.

**Comment by racuna** [comment]
Yeah @X-dark, that's the main difference between versions. But I currently do not have Events, only Conditions.

Maybe is a change in the syntax of the json files, I dunno.

**Comment by X-dark** [comment]
What I meant is, if code for condition and event have been merged, perhaps the bug occurring with events has been propagated to condition as well.

**Comment by racuna** [comment]
Yeah, I hope the dev can find the solution soon :)

**Comment by renyuneyun** [comment]
Thanks for reporting, guys.
The error log shows the problem is related to the data parsing backend. I'll dig further soon.
It's likely a problem with the change (update) of data content.

**Comment by BN5JM** [comment]
I found a basic fix for the crashing and some options not being clickable.
The solution requires clearing Easers storage. The problem with this solution is that all Scripts, Profiles, etc. are removed. So, if you have something elaborate and don't want to recreate it, I would hold off until a proper solution is created.

Solution:
1. Go into your phone's setting and then into Apps & notifications
2. Find Easer and click on Storage then click on CLEAR STORAGE and maybe CLEAR CACHE for safe measure
3. Once you've done that, open Easer, grant it the permissions and start recreating your scripts

Hope this helps :)

**Comment by renyuneyun** [comment]
I figured out.
I was silly: a skill (Connectivity) was not added to the registry at v0.7.7 (because I converted many Condition and Event to USource).

This should be fixed in c563dc29c6ada57e5c8d61e9c736f6842bc63cf2 . It should appear in v0.7.7.6 (without beta).

The issue will automatically be closed when that commit is merged into master, which in turn means a release (but f-droid may delay a few days).
Feel free to reopen this issue if otherwise.

**Comment by gruentee** [comment]
I still have this issue on latest (F-Droid) version 0.7.7.6.

**Comment by mmoole** [comment]
Hi, I am also having this problem, but without updating. I just installed Easer 0.7.7.6 via F-Droid on Lenovo z90a40 stock Android 6.0.1.
That's what I saw (and what is in the log file): [logcat-z90a40-2019-08-10-easer_v1.log](https://github.com/renyuneyun/Easer/files/3488739/logcat-z90a40-2019-08-10-easer_v1.log)
* blank screen for several seconds, then with message about easer crashed and hint to logfile (but there is none at /sdcard/logger/...)
* introduction steps for easer: I tapped next every screen
* blank screen for a short time/quit of easer app.
